In [5]:
import matplotlib.pyplot as plt 
import pandas as pd
import numpy as np
import networkx as nx
%matplotlib inline

In [6]:
df = pd.read_csv('data/total/total.csv', header = 0, index_col = 0)

In [4]:
df.head()

,Classification,Year,Period,Period Desc.,Aggregate Level,Is Leaf Code,Trade Flow Code,Trade Flow,Reporter Code,Reporter,...,Qty,Alt Qty Unit Code,Alt Qty Unit,Alt Qty,Netweight (kg),Gross weight (kg),Trade Value (US$),CIF Trade Value (US$),FOB Trade Value (US$),Flag
0,H4,2013,2013,2013,4,0,1,Import,703,Slovakia,...,179681813.0,NaN,NaN,NaN,NaN,NaN,13281084,NaN,NaN,6
1,H4,2013,2013,2013,4,0,2,Export,703,Slovakia,...,42857330.0,NaN,NaN,NaN,42857330.0,NaN,29925089,NaN,NaN,6
2,H4,2013,2013,2013,4,0,4,Re-Import,703,Slovakia,...,59646.0,NaN,NaN,NaN,59646.0,NaN,52688,NaN,NaN,0
3,H4,2013,2013,2013,6,1,1,Import,703,Slovakia,...,145531934.0,NaN,NaN,NaN,NaN,NaN,4906274,NaN,NaN,6
4,H4,2013,2013,2013,6,1,2,Export,703,Slovakia,...,11494087.0,NaN,NaN,NaN,11494087.0,NaN,5898433,NaN,NaN,6

## Average

In [127]:
im_df = df[(df['Trade Flow'] == 'Import') & (df['Year'].isin([2017,2018, 2019]))]

In [128]:
im_df.columns

Index(['Classification', 'Year', 'Period', 'Period Desc.', 'Aggregate Level',
       'Is Leaf Code', 'Trade Flow Code', 'Trade Flow', 'Reporter Code',
       'Reporter', 'Reporter ISO', 'Partner Code', 'Partner', 'Partner ISO',
       '2nd Partner Code', '2nd Partner', '2nd Partner ISO',
       'Customs Proc. Code', 'Customs', 'Mode of Transport Code',
       'Mode of Transport', 'Commodity Code', 'Commodity', 'Qty Unit Code',
       'Qty Unit', 'Qty', 'Alt Qty Unit Code', 'Alt Qty Unit', 'Alt Qty',
       'Netweight (kg)', 'Gross weight (kg)', 'Trade Value (US$)',
       'CIF Trade Value (US$)', 'FOB Trade Value (US$)', 'Flag'],
      dtype='object')

In [129]:
im_df.shape

(24340, 35)

In [90]:
im_df.head()

,Classification,Year,Period,Period Desc.,Aggregate Level,Is Leaf Code,Trade Flow Code,Trade Flow,Reporter Code,Reporter,...,Qty,Alt Qty Unit Code,Alt Qty Unit,Alt Qty,Netweight (kg),Gross weight (kg),Trade Value (US$),CIF Trade Value (US$),FOB Trade Value (US$),Flag
29924,H5,2018,2018,2018,4,0,1,Import,96,Brunei Darussalam,...,124762.0,NaN,NaN,NaN,124762.0,NaN,261725,NaN,NaN,6
29927,H5,2018,2018,2018,6,1,1,Import,96,Brunei Darussalam,...,124542.0,NaN,NaN,NaN,124542.0,NaN,238111,NaN,NaN,6
29932,H5,2018,2018,2018,6,1,1,Import,96,Brunei Darussalam,...,220.0,NaN,NaN,NaN,220.0,NaN,23614,NaN,NaN,0
29933,H5,2018,2018,2018,6,1,1,Import,96,Brunei Darussalam,...,220.0,NaN,NaN,NaN,220.0,NaN,23614,NaN,NaN,0
29934,H5,2018,2018,2018,6,1,1,Import,96,Brunei Darussalam,...,74624.0,NaN,NaN,NaN,74624.0,NaN,102197,NaN,NaN,0

In [130]:
'''remove world'''
im_df = im_df[(im_df['Partner'] != 'World') & (im_df['Reporter'] != 'World')]
im_df = im_df[(im_df['Partner'] != 'EU-28') & (im_df['Reporter'] != 'EU-28')]
im_df = im_df[(im_df['Partner'] != 'Other Europe, nes') & (im_df['Reporter'] != 'Other Europe, nes')]
im_df = im_df[(im_df['Partner'] != 'LAIA, nes') & (im_df['Reporter'] != 'LAIA, nes')]
im_df = im_df[(im_df['Partner'] != 'Oceania, nes') & (im_df['Reporter'] != 'Oceania, nes')]
im_df = im_df[(im_df['Partner'] != 'ASEAN') & (im_df['Reporter'] != 'ASEAN')]
im_df = im_df[(im_df['Partner'] != 'Other Asia, nes') & (im_df['Reporter'] != 'Other Asia, nes')]

In [131]:
im_sum_df = im_df.groupby(['Partner', 'Reporter'])['Netweight (kg)'].mean()

In [132]:
im_sum_df =im_sum_df.to_frame()

In [133]:
im_sum_df = im_sum_df.rename({'Reporter':'Reporter', 'Netweight (kg)':'Mean_kg'}, axis = 'columns')
im_sum_df.head()

                                   Mean_kg
Partner Reporter
Albania Bulgaria              5.432268e+05
        China, Hong Kong SAR  8.969200e+04
        Greece                1.028891e+06
        Italy                 1.261837e+05
        North Macedonia       1.279406e+06

In [102]:
im_sum_df.index

MultiIndex([( 'Albania',               'Bulgaria'),
            ( 'Albania',   'China, Hong Kong SAR'),
            ( 'Albania',                 'Greece'),
            ( 'Albania',                  'Italy'),
            ( 'Albania',        'North Macedonia'),
            ( 'Albania',                'Romania'),
            ( 'Albania',           'Sierra Leone'),
            ( 'Albania',                 'Turkey'),
            ( 'Albania',   'United Arab Emirates'),
            ( 'Algeria',                'Austria'),
            ...
            (  'Zambia',                  'China'),
            (  'Zambia', 'Dem. Rep. of the Congo'),
            (  'Zambia',             'Mozambique'),
            (  'Zambia',           'South Africa'),
            (  'Zambia',                 'Uganda'),
            (  'Zambia',   'United Arab Emirates'),
            ('Zimbabwe',                  'China'),
            ('Zimbabwe',   'China, Hong Kong SAR'),
            ('Zimbabwe',                 'Malawi'),
            ('Zimbabwe',           'South Africa')],
           names=['Partner', 'Reporter'], length=3720)

In [134]:
''' Record by quantile'''
for temp_q in [0.8, 0.6, 0.5, 0.2] : 
    im_sum_df = im_sum_df[im_sum_df['Mean_kg'] > im_sum_df.Mean_kg.quantile(temp_q)]
    f = open('%s/Im_Top%s_before2020_mean_kg.csv' %(data_read_path, temp_q), 'w')
    for (temp_i, temp_j) in im_sum_df.index : 
        temp_kg = im_sum_df.loc[(temp_i, temp_j), 'Mean_kg']
        print(temp_i,'\t',temp_j,'\t',temp_kg, file = f)
    f.close()

In [159]:
''' 2020 '''
im_df = df[(df['Trade Flow'] == 'Import') & (df['Year'].isin([2020]))]
'''remove world'''
im_df = im_df[(im_df['Partner'] != 'World') & (im_df['Reporter'] != 'World')]
im_df = im_df[(im_df['Partner'] != 'EU-28') & (im_df['Reporter'] != 'EU-28')]
im_df = im_df[(im_df['Partner'] != 'Other Europe, nes') & (im_df['Reporter'] != 'Other Europe, nes')]
im_df = im_df[(im_df['Partner'] != 'LAIA, nes') & (im_df['Reporter'] != 'LAIA, nes')]
im_df = im_df[(im_df['Partner'] != 'Oceania, nes') & (im_df['Reporter'] != 'Oceania, nes')]
im_df = im_df[(im_df['Partner'] != 'ASEAN') & (im_df['Reporter'] != 'ASEAN')]
im_df = im_df[(im_df['Partner'] != 'Other Asia, nes') & (im_df['Reporter'] != 'Other Asia, nes')]

im_sum_df = im_df.groupby(['Partner', 'Reporter'])['Netweight (kg)'].mean()
im_sum_df =im_sum_df.to_frame()
im_sum_df = im_sum_df.rename({'Reporter':'Reporter', 'Netweight (kg)':'Mean_kg'}, axis = 'columns')

''' Record by quantile'''
for temp_q in [0.8, 0.6, 0.5, 0.2] : 
    im_sum_df = im_sum_df[im_sum_df['Mean_kg'] > im_sum_df.Mean_kg.quantile(temp_q)]
    f = open('%s/Im_Top%s_in2020_mean_kg.csv' %(data_read_path, temp_q), 'w')
    print('Source','\t','Target','\t','Weight',file = f )
    for (temp_i, temp_j) in im_sum_df.index : 
        temp_kg = im_sum_df.loc[(temp_i, temp_j), 'Mean_kg']
        print(temp_i,'\t',temp_j,'\t',temp_kg, file = f)
    f.close()

## Average Export

In [160]:
''' Before 2020 '''
im_df = df[(df['Trade Flow'] == 'Export') & (df['Year'].isin([2017, 2018, 2019]))]
'''remove world'''
im_df = im_df[(im_df['Partner'] != 'World') & (im_df['Reporter'] != 'World')]
im_df = im_df[(im_df['Partner'] != 'EU-28') & (im_df['Reporter'] != 'EU-28')]
im_df = im_df[(im_df['Partner'] != 'Other Europe, nes') & (im_df['Reporter'] != 'Other Europe, nes')]
im_df = im_df[(im_df['Partner'] != 'LAIA, nes') & (im_df['Reporter'] != 'LAIA, nes')]
im_df = im_df[(im_df['Partner'] != 'Oceania, nes') & (im_df['Reporter'] != 'Oceania, nes')]
im_df = im_df[(im_df['Partner'] != 'ASEAN') & (im_df['Reporter'] != 'ASEAN')]
im_df = im_df[(im_df['Partner'] != 'Other Asia, nes') & (im_df['Reporter'] != 'Other Asia, nes')]

im_sum_df = im_df.groupby(['Partner', 'Reporter'])['Netweight (kg)'].mean()
im_sum_df =im_sum_df.to_frame()
im_sum_df = im_sum_df.rename({'Reporter':'Reporter', 'Netweight (kg)':'Mean_kg'}, axis = 'columns')
print(im_sum_df.head())
''' Record by quantile'''
for temp_q in [0.8, 0.6, 0.5, 0.2] : 
    im_sum_df = im_sum_df[im_sum_df['Mean_kg'] > im_sum_df.Mean_kg.quantile(temp_q)]
    f = open('%s/Ex_Top%s_before2020_mean_kg.csv' %(data_read_path, temp_q), 'w')
    print('Source','\t','Target','\t','Weight',file = f )
    for (temp_j, temp_i) in im_sum_df.index : 
        temp_kg = im_sum_df.loc[(temp_j, temp_i), 'Mean_kg']
        print(temp_i,'\t',temp_j,'\t',temp_kg, file = f)
    f.close()

                                  Mean_kg
Partner     Reporter
Afghanistan Iran                1239347.2
            Pakistan             314776.0
            Russian Federation    20000.0
            Turkey                25850.0
            USA                   12359.0

In [161]:
''' in 2020 '''
im_df = df[(df['Trade Flow'] == 'Export') & (df['Year'].isin([2020]))]
'''remove world'''
im_df = im_df[(im_df['Partner'] != 'World') & (im_df['Reporter'] != 'World')]
im_df = im_df[(im_df['Partner'] != 'EU-28') & (im_df['Reporter'] != 'EU-28')]
im_df = im_df[(im_df['Partner'] != 'Other Europe, nes') & (im_df['Reporter'] != 'Other Europe, nes')]
im_df = im_df[(im_df['Partner'] != 'LAIA, nes') & (im_df['Reporter'] != 'LAIA, nes')]
im_df = im_df[(im_df['Partner'] != 'Oceania, nes') & (im_df['Reporter'] != 'Oceania, nes')]
im_df = im_df[(im_df['Partner'] != 'ASEAN') & (im_df['Reporter'] != 'ASEAN')]
im_df = im_df[(im_df['Partner'] != 'Other Asia, nes') & (im_df['Reporter'] != 'Other Asia, nes')]

im_sum_df = im_df.groupby(['Partner', 'Reporter'])['Netweight (kg)'].mean()
im_sum_df =im_sum_df.to_frame()
im_sum_df = im_sum_df.rename({'Reporter':'Reporter', 'Netweight (kg)':'Mean_kg'}, axis = 'columns')

''' Record by quantile'''
for temp_q in [0.8, 0.6, 0.5, 0.2] : 
    im_sum_df = im_sum_df[im_sum_df['Mean_kg'] > im_sum_df.Mean_kg.quantile(temp_q)]
    f = open('%s/Ex_Top%s_in2020_mean_kg.csv' %(data_read_path, temp_q), 'w')
    print('Source','\t','Target','\t','Weight',file = f )
    for (temp_j, temp_i) in im_sum_df.index : 
        temp_kg = im_sum_df.loc[(temp_j, temp_i), 'Mean_kg']
        print(temp_i,'\t',temp_j,'\t',temp_kg, file = f)
    f.close()

## Network Top rank change?

### Import (Before 2020)

In [163]:
Quantile = 0.2
before_imG = nx.read_edgelist('%s/Im_Top%s_before2020_mean_kg.csv' %(data_read_path, Quantile),\
                      create_using = nx.DiGraph(), delimiter = '\t', \
                    comments = 'Source', data = (("weight", float),))

before_im_cendf = pd.DataFrame(index = before_imG.nodes()) 
print(len(list(before_imG.nodes())))
ind_cen = nx.in_degree_centrality(before_imG) # no weight
eig_cen = nx.eigenvector_centrality(before_imG, weight = 'weight') # weight 
katz_cen = nx.katz_centrality(before_imG, weight = 'weight') # weight 

''' add to df '''
before_im_cendf['Indgr_cen'] = before_im_cendf.index.map(ind_cen)
before_im_cendf['Eig_cen'] = before_im_cendf.index.map(eig_cen)
before_im_cendf['Katz_cen'] = before_im_cendf.index.map(katz_cen)
before_im_cendf.to_csv('%s/Im_Before2020_Top%s_centrality.csv' %(data_read_path, Quantile), sep = '\t')

72

#### Import (in 2020)

In [164]:
Quantile = 0.2
before_imG = nx.read_edgelist('%s/Im_Top%s_in2020_mean_kg.csv' %(data_read_path, Quantile),\
                      create_using = nx.DiGraph(), delimiter = '\t', comments = 'Source', data = (("weight", float),))

before_im_cendf = pd.DataFrame(index = before_imG.nodes()) 
print(len(list(before_imG.nodes())))
ind_cen = nx.in_degree_centrality(before_imG) # no weight
eig_cen = nx.eigenvector_centrality(before_imG, weight = 'weight') # weight 
katz_cen = nx.katz_centrality(before_imG, weight = 'weight') # weight 

''' add to df '''
before_im_cendf['Indgr_cen'] = before_im_cendf.index.map(ind_cen)
before_im_cendf['Eig_cen'] = before_im_cendf.index.map(eig_cen)
before_im_cendf['Katz_cen'] = before_im_cendf.index.map(katz_cen)
before_im_cendf.to_csv('%s/Im_in2020_Top%s_centrality.csv' %(data_read_path, Quantile), sep = '\t')

33

### Export (before 2020)

In [165]:
Quantile = 0.2
before_imG = nx.read_edgelist('%s/Ex_Top%s_before2020_mean_kg.csv' %(data_read_path, Quantile),\
                      create_using = nx.DiGraph(), delimiter = '\t', comments = 'Source', data = (("weight", float),))

before_im_cendf = pd.DataFrame(index = before_imG.nodes()) 
print(len(list(before_imG.nodes())))
ind_cen = nx.in_degree_centrality(before_imG) # no weight
eig_cen = nx.eigenvector_centrality(before_imG, weight = 'weight') # weight 
katz_cen = nx.katz_centrality(before_imG, weight = 'weight') # weight 

''' add to df '''
before_im_cendf['Indgr_cen'] = before_im_cendf.index.map(ind_cen)
before_im_cendf['Eig_cen'] = before_im_cendf.index.map(eig_cen)
before_im_cendf['Katz_cen'] = before_im_cendf.index.map(katz_cen)
before_im_cendf.to_csv('%s/Ex_Before2020_Top%s_centrality.csv' %(data_read_path, Quantile), sep = '\t')

65

In [166]:
Quantile = 0.2
before_imG = nx.read_edgelist('%s/Ex_Top%s_in2020_mean_kg.csv' %(data_read_path, Quantile),\
                      create_using = nx.DiGraph(), delimiter = '\t', comments = 'Source', data = (("weight", float),))

before_im_cendf = pd.DataFrame(index = before_imG.nodes()) 
print(len(list(before_imG.nodes())))
ind_cen = nx.in_degree_centrality(before_imG) # no weight
eig_cen = nx.eigenvector_centrality(before_imG, weight = 'weight') # weight 
katz_cen = nx.katz_centrality(before_imG, weight = 'weight') # weight 

''' add to df '''
before_im_cendf['Indgr_cen'] = before_im_cendf.index.map(ind_cen)
before_im_cendf['Eig_cen'] = before_im_cendf.index.map(eig_cen)
before_im_cendf['Katz_cen'] = before_im_cendf.index.map(katz_cen)
before_im_cendf.to_csv('%s/Ex_in2020_Top%s_centrality.csv' %(data_read_path, Quantile), sep = '\t')

35